name: Deploy to DigitalOcean
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  SSH-into-droplet:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.BOOKMARK_DROPLET_PRIVATE_KEY }}
      DROPLET_IP: ${{ vars.BOOKMARK_DROPLET_IP }}
    steps:
      - run: echo "Deploying to DigitalOcean..."
      - name: Generate tag
        id: tag
        run: echo "::set-output name=tag::notion-telegram-bookmark:$(date +%s)"
      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ steps.tag.outputs.tag }}
      - name: Copy the Docker image
        run: docker save ${{ steps.tag.outputs.tag }} | bzip2 | ssh root@$DROPLET_IP docker load
      - name: Remove old containers
        run: |
          ssh root@$DROPLET_IP 'docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)'
      - name: Deploy to Remote Server
        run: |
          ssh root@$DROPLET_IP 'docker run -p 3000:3000 --name notion-telegram-bookmark --env-file .env -d ${{ steps.tag.outputs.tag }}'
