name: Deploy to DigitalOcean
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  SSH-into-droplet:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.BOOKMARK_DROPLET_PRIVATE_KEY }}
      DROPLET_IP: ${{ vars.BOOKMARK_DROPLET_IP }}
    steps:
      - run: echo "Deploying to DigitalOcean..."
      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts

      - name: Deploy to Remote Server
        run: |
          ssh root@$DROPLET_IP 'source ~/.nvm/nvm.sh && cd notion-telegram-bookmark && git pull && npm run deploy'
