name: Deploy to DigitalOcean
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  SSH-into-droplet:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.BOOKMARK_DROPLET_PRIVATE_KEY }}
      DROPLET_IP: ${{ vars.BOOKMARK_DROPLET_IP }}
      TAG: notion-telegram-bookmark:$(date +%s)
    steps:
      - run: echo "Deploying to DigitalOcean..."
      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $TAG
      - name: Copy the Docker image
        run: docker save $TAG | bzip2 | ssh bookmark-droplet docker load
      - name: Deploy to Remote Server
        run: |
          ssh root@$DROPLET_IP 'cd notion-telegram-bookmark && docker run -p 3000:3000 --env-file .env $TAG'
