name: Deploy to DigitalOcean
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  SSH-into-droplet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to DigitalOcean at $BOOKMARK_DROPLET_IP..."
      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$BOOKMARK_DROPLET_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $BOOKMARK_DROPLET_IP >> ~/.ssh/known_hosts

      - name: Deploy to Remote Server
        run: |
          ssh root@$BOOKMARK_DROPLET_IP 'cd notion-telegram-bookmark && git pull && npm run deploy'
